### ISSUE TITLE
What should functions do with xpath expressions that return multiple nodes.

### ISSUE THREAD

**Issue by buckett** [TEIC/TEI-Simple#1]
Functions often take an xpath expression and in the examples it's
often the current node, but what should happen if the xpath expression
returns multiple nodes?

```
<model behaviour="block(.//)"/>
```

Here we're returning all nodes below the current node as asking them to be formatted as block(wrapped with a `<div>`)

**Comment by sebastianrahtz** [comment]
This behaves like xsl apply-templates. the task is to visit all the children of the identified nodes and process them using the usual rules.

Your .// isn't valid XPath :-}

**Comment by buckett** [comment]
Ok so my example should be `descendant-or-self::*`, but to confirm I should build a block for each encountered node?

**Comment by sebastianrahtz** [comment]
hmm. no. you build a block for the current node, wrapped around the
processing of descendant-or-self::\* and whatever they ask for.

On 24 March 2015 at 16:01, Matthew Buckett notifications@github.com wrote:

> Ok so my example should be descendant-or-self::*, but to confirm I should
> build a block for each encountered node?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TEIC/TEI-Simple/issues/1#issuecomment-85577081.

## 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431

Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.
