### ISSUE TITLE
Heads-up on att.global vs att.global.rendition

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI-Simple#10]
The current ODD file modifies att.global to remove @style and @rend and customize @rendition. Those attributes will be in att.global.rendition rather than att.global in the next release. Just a warning that things will break when that happens.

**Comment by sebastianrahtz** [comment]
drat. can't decide whether to anticipate this or change later

On 24 March 2015 at 16:41, Martin Holmes notifications@github.com wrote:

> The current ODD file modifies att.global to remove @style
> https://github.com/style and @rend https://github.com/rend and
> customize @rendition https://github.com/rendition. Those attributes
> will be in att.global.rendition rather than att.global in the next release.
> Just a warning that things will break when that happens.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TEIC/TEI-Simple/issues/10.

## 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431

Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.

**Comment by sebastianrahtz** [comment]
done now
