### ISSUE TITLE
Why no simple:justified?

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI-Simple#11]
simple:left, simple:right and simple:centre are included, but there's no simple:justify or simple:justified. This does exist -- see, for instance, the italicized block at the bottom of the first column on this page:

http://internetshakespeare.uvic.ca/Library/facsimile/book/SLNSW_F1/567/?zoom=850

so I think it should be included.

**Comment by sebastianrahtz** [comment]
very fair point. am duly adding it now.

On 11 April 2015 at 02:20, Martin Holmes notifications@github.com wrote:

> simple:left, simple:right and simple:centre are included, but there's no
> simple:justify or simple:justified. This does exist -- see, for instance,
> the italicized block at the bottom of the first column on this page:
> 
> http://internetshakespeare.uvic.ca/Library/facsimile/book/SLNSW_F1/567/?zoom=850
> 
> so I think it should be included.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TEIC/TEI-Simple/issues/11.

## 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431

Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.

**Comment by martindholmes** [comment]
Are you calling it simple:justify or simple:justified? I'm already using it so I want to name it right. :-)

**Comment by Conal-Tuohy** [comment]
CSS calls it "justify"

**Comment by martindholmes** [comment]
That's what I prefer too. I like "simple:centre" with "re" spelling, though, in defiance of W3C. :-)

**Comment by sebastianrahtz** [comment]
justify it is
