### ISSUE TITLE
name type="organization" is out of line with existing TEI practice

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI-Simple#17]
For a long time, we have had the notion that e.g. `<orgName>` is syntactic sugar for `<name type="org">` and we even have an example of @type="org" in the Guidelines:

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-name.html

Why does Simple adopt the unconventional `<name type="organization">`?

`<name type="placeGeog">` is even weirder, alongside `<name type="place">`. Aren't all geographical names places? Why not `<name type="geog">`?

**Comment by martindholmes** [comment]
Even worse: it's actually "organisation" with an "s".

**Comment by PFSchaffner** [comment]
Hmm. Suspicions on fall on either an American (hypercorrecting the Anglo-American 'organization' to a putative British '*organisation') -- or someone French using French spelling.

**Comment by sebastianrahtz** [comment]
Nasty one. You're probably right, i just dont like the idea of perpetuating
 a short non-word like "org". Will change this.

On 4 June 2015 at 21:59, Martin Holmes notifications@github.com wrote:

> For a long time, we have had the notion that e.g. <orgName> is syntactic
> sugar for <name type="org"> and we even have an example of @type
> https://github.com/type="org" in the Guidelines:
> 
> http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-name.html
> 
> Why does Simple adopt the unconventional <name type="organization">?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TEIC/TEI-Simple/issues/17.

## 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431

Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.
