### ISSUE TITLE
simple:letterspace: what does it mean?

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI-Simple#18]
Unless this is a technical term from typography that I don't know, simple:letterspace is a bit confusing; it doesn't say what the size of the letter spacing is (wider than normal, narrower than normal?). Isn't it a bit like saying "font-size" without providing a size? If it's analogous to CSS letter-spacing, it needs a value of some kind, surely?

**Comment by sebastianrahtz** [comment]
Hmm. To me its just a term from typography meaning "extra spacing between
letters". _less_ spacing between letters doesnt really exist in traditional
typography.

On 4 June 2015 at 22:31, Martin Holmes notifications@github.com wrote:

> Unless this is a technical term from typography that I don't know,
> simple:letterspace is a bit confusing; it doesn't say what the size of the
> letter spacing is (wider than normal, narrower than normal?). Isn't it a
> bit like saying "font-size" without providing a size? If it's analogous to
> CSS letter-spacing, it needs a value of some kind, surely?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TEIC/TEI-Simple/issues/18.

## 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431

Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.

**Comment by martinmueller39** [comment]
Is that what the Germans call "Sperrtext" You put a space between letters for e m p h a s I s

**Comment by lb42** [comment]
You might use a particular kind of letterspacing to achieve that effect, 
but the term itself is used typographically to describe _how much_ space 
there is between all the characters in one line. Distinguished from 
"kerning" which just applies to a pair of adjacent letters.

Soo you probably shouldnt be using it to mean just "more letterspace 
than normal" -- if you do, how would you say "less letterspace than 
usual"? May I suggest "looseSpace" and "tightSpace" (respectively) as 
more amusing alternative names?

However, according to http:// 
practicaltypography.com/_letterspacing_.html it isnt currently used to 
do anything other than promote looseness.

**Comment by sebastianrahtz** [comment]
Sent from my iPhone

> On 7 Jun 2015, at 14:32, martinmueller39 notifications@github.com wrote:
> 
> Is that what the Germans call "Sperrtext" You put a space between letters for e m p h a s I s

Yes, that's just what I am thinking off. Disgusting technique ..,

Sebastian

**Comment by martinmueller39** [comment]
I don't like it much myself, but it is quite common in earlier books. More common on the Continent, I think , than in the Anglo world. And if my visual memory doesn't trick me, the space between the letters is less than the space between words. But I'm not sure about that.

**Comment by sebastianrahtz** [comment]
On 7 June 2015 at 15:02, martinmueller39 notifications@github.com wrote:

> I don't like it much myself, but it is quite common in earlier books. More
> common on the Continent, I think , than in the Anglo world. And if my
> visual memory doesn't trick me, the space between the letters is less than
> the space between words. But I'm not sure about that.
> 
> not the same, of course, as using the same trick to justify paragraphs,
> which is simply evil. I agree,
> its a European thing. I claim its use to _lessen_ letter-spacing is so rare
> that I am going to leave this
> one as is/

Sebastian

**Comment by martindholmes** [comment]
Keep the ident value, fair enough, but please clarify the desc so that ignoramuses like me with a CSS understanding can figure out what it means. Could I suggest "larger-than-normal spacing between letters, usually for emphasis"?

**Comment by sebastianrahtz** [comment]
you got it

On 7 June 2015 at 20:41, Martin Holmes notifications@github.com wrote:

> Keep the ident value, fair enough, but please clarify the desc so that
> ignoramuses like me with a CSS understanding can figure out what it means.
> Could I suggest "larger-than-normal spacing between letters, usually for
> emphasis"?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TEIC/TEI-Simple/issues/18#issuecomment-109792296.

## 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431

Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.
