### ISSUE TITLE
Why `<gi>` and `<att>` but not `<val>`?

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI-Simple#19]
I could understand Simple not having any of these three elements, but to have two and not the third seems strange; is there a reason for it? I typically use all three when documenting encoding practices.

**Comment by sydb** [comment]
It does seem a bit disorganized. I typically use all four (<gi>,
<att>, <val>, and <tag>) or none.

> I could understand Simple not having any of these three elements,
> but to have two and not the third seems strange; is there a reason
> for it? I typically use all three when documenting encoding
> practices.

**Comment by lb42** [comment]
I cannot see any justification for having any of them in simple, unless there has been some mission creep...

**Comment by martindholmes** [comment]
I think you'd use them in encodingDesc, and Simple's approach has been (I think) largely to leave the header alone. Paul is right, though: `<tag>` is missing too.

**Comment by martinmueller39** [comment]
That seems right to me.

**Comment by sebastianrahtz** [comment]
I will add these extras to the list of elements only allowed in the header
