### ISSUE TITLE
Is a <modelSequence> allowed inside a <modelGrp>

### ISSUE THREAD

**Issue by buckett** [TEIC/TEI-Simple#2]
Should you be able to place a `<modelSequence>` inside a `<modelGrp>`?

Currently there is an example of this:

https://github.com/TEIC/TEI-Simple/blob/master/tei-pm.odd#L656

However the specification of a `<modelSequence>` says it should only contain a number of `<model>`s:

https://github.com/TEIC/TEI-Simple/blob/master/tei-pm.odd#L553

**Comment by sebastianrahtz** [comment]
the definition of modelGrp was in error; it should permit modelSequence inside it. Also corrected `<classRef>` there to `<elementRef>`
