### ISSUE TITLE
Is there a dtd? 

### ISSUE THREAD

**Issue by JonathanReeve** [TEIC/TEI-Simple#23]
Sorry if this is a silly question, but is there a TEI Simple DTD file somewhere? I notice it's referenced in `tests/testsimple.xml`, but I don't see it in the parent directory.

**Comment by lb42** [comment]
As with other TEI schemes, it's always possible to generate a DTD from the ODD specification (teisimple.odd), using e.g. the online Roma tool, or a command line utility such as teitodtd. I don't think anyone's bothered to make a DTD : there are RELAXNG schemas at teisimple.rng and teisimple.rnc, and a W3C schema version at teisimple.xsd

**Comment by lb42** [comment]
... and there is one now!

**Comment by JonathanReeve** [comment]
Awesome, thanks! I'd been having difficulty validating against a RELAX NG schema. `xmllint --valid --relaxng teisimple.rng test-tei-simple.xml` just sits there, not doing anything. But it seems to validate against DTDs.
