### ISSUE TITLE
There's no specification on how a <modelGrp> uses it's own <rendition>

### ISSUE THREAD

**Issue by buckett** [TEIC/TEI-Simple#3]
The specification says that a `<modelGrp>` can have its own `<rendition>`:

https://github.com/TEIC/TEI-Simple/blob/master/tei-pm.odd#L602

but there is no example or elaboration about how this should be handled.

**Comment by lb42** [comment]
Weirder still, the spec at that point actually says <classRef 
key="rendition"/>  : there is no class called rendition, so this is 
meaningless.

**Comment by tuurma** [comment]
If I remember correctly modelGrp was meant just to group stuff for better
readability, therefore if there's a rendition for a modelGrp it should be
inherited by all model children.

**Comment by sebastianrahtz** [comment]
Yes, tuurma is right. A modelGrp can be simply expanded and pass its attributes into its children.
