### ISSUE TITLE
What version of XPath are all the XPath expressions?

### ISSUE THREAD

**Issue by buckett** [TEIC/TEI-Simple#4]
Currently the specification refers to XPath expressions but doesn't elaborate as to which version of XPath should be used.

**Comment by sebastianrahtz** [comment]
thats a good question! not 1.0, so probably 2.0. We need to change the spec to say so. Does it present a problem?

**Comment by buckett** [comment]
In Java requiring XPath 2 means that Saxon-HE looks to be the only realistic implementation.

**Comment by sebastianrahtz** [comment]
Yes, thats a not a surprise. It's used so widely already that  I dont see
it as a problem. Pity, but XPath 2.0 is just too well-known.

On 24 March 2015 at 16:03, Matthew Buckett notifications@github.com wrote:

> In Java requiring XPath 2 means that Saxon-HE looks to be the only
> realistic implementation.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TEIC/TEI-Simple/issues/4#issuecomment-85578331.

## 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431

Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.
