### ISSUE TITLE
How should a function behave when it's XPath expression doesn't return anything?

### ISSUE THREAD

**Issue by buckett** [TEIC/TEI-Simple#5]
How should a function behave when its XPath expression doesn't return anything. If it's a function that outputs some content (`block(../element)`) should the output container still be written? I'm guessing not, but it's not explicit in the specification.

**Comment by lb42** [comment]
The purpose of the Xpath is presumably to specify the content of the output container, not the container itself. So I think it ought to return an empty output container.

**Comment by tuurma** [comment]
We probably need to discuss this one. It is possible to want to have some output when the content is empty (`<gap/>` elements would be an example: content is empty, but you typically want to put in some placeholder like [...], so you'd have rendition & scope and would need an inline element to attach it to.

**Comment by sebastianrahtz** [comment]
I agree with Lou. You dont need to clean up after people. If they write XPath which returns no content, you should produce an empty container.
