### ISSUE TITLE
Do implementers need to support <rendition scheme="css">

### ISSUE THREAD

**Issue by buckett** [TEIC/TEI-Simple#7]
The `<rendition>` tag can have a scheme attribute:

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-rendition.html
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.styleDef.html

Do implementors of the specification need to worry about this attribute?

**Comment by tuurma** [comment]
CSS will be the only option for TEI Simple. Implementors do not need to worry about the attribute then but still need to worry about CSS support :)

**Comment by buckett** [comment]
But presumably I don't want to include a `<rendition scheme="xslfo">` in my document so I need to be aware of this attribute. Therefore I need to only examine tags that have no scheme attribute and those that have it set to `css`.

**Comment by tuurma** [comment]
This we probably need to decide: do we keep @scheme on rendition at all or
not. I assume not but may be proven wrong.

**Comment by buckett** [comment]
The `useSourceRendition` attribute would also mean an implementor would have to understand examples where the rendition refers to a rendition contained elsewhere in the document:

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.html#tei_att.rendition

which again may introduce the standard rendition attributes.

**Comment by sebastianrahtz** [comment]
the `<rendition>` has been renamed `<outputRendition>` and now has no @scheme
