### ISSUE TITLE
Strange value/gloss for @place

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI-Simple#9]
This in teisimple.odd is a bit puzzling:

valItem ident="display"
  desc: formatted like a quotation

What does "formatted like a quotation" mean, and why would a value of "display" map to this?

**Comment by sebastianrahtz** [comment]
changed to
`<valItem ident="block">
                      <desc>formatted as an indented paragraph</desc>
 </valItem>`

which I hope makes more sense.

**Comment by adunning** [comment]
Should 'simple:display' in @rendition also be renamed to match this?

**Comment by sebastianrahtz** [comment]
I concur. duly use "block instead of "display" passim et seriatim
